// SPDX-FileCopyrightText: Copyright 2026 Stacklok, Inc.
// SPDX-License-Identifier: Apache-2.0
//

// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -copyright_file=../../.github/license-header.txt -source=interfaces.go -destination=mocks/mock_interfaces.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	digest "github.com/opencontainers/go-digest"
	skills "github.com/stacklok/toolhive-core/oci/skills"
	gomock "go.uber.org/mock/gomock"
)

// MockRegistryClient is a mock of RegistryClient interface.
type MockRegistryClient struct {
	ctrl     *gomock.Controller
	recorder *MockRegistryClientMockRecorder
	isgomock struct{}
}

// MockRegistryClientMockRecorder is the mock recorder for MockRegistryClient.
type MockRegistryClientMockRecorder struct {
	mock *MockRegistryClient
}

// NewMockRegistryClient creates a new mock instance.
func NewMockRegistryClient(ctrl *gomock.Controller) *MockRegistryClient {
	mock := &MockRegistryClient{ctrl: ctrl}
	mock.recorder = &MockRegistryClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRegistryClient) EXPECT() *MockRegistryClientMockRecorder {
	return m.recorder
}

// Pull mocks base method.
func (m *MockRegistryClient) Pull(ctx context.Context, store *skills.Store, ref string) (digest.Digest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pull", ctx, store, ref)
	ret0, _ := ret[0].(digest.Digest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Pull indicates an expected call of Pull.
func (mr *MockRegistryClientMockRecorder) Pull(ctx, store, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pull", reflect.TypeOf((*MockRegistryClient)(nil).Pull), ctx, store, ref)
}

// Push mocks base method.
func (m *MockRegistryClient) Push(ctx context.Context, store *skills.Store, manifestDigest digest.Digest, ref string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Push", ctx, store, manifestDigest, ref)
	ret0, _ := ret[0].(error)
	return ret0
}

// Push indicates an expected call of Push.
func (mr *MockRegistryClientMockRecorder) Push(ctx, store, manifestDigest, ref any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Push", reflect.TypeOf((*MockRegistryClient)(nil).Push), ctx, store, manifestDigest, ref)
}

// MockSkillPackager is a mock of SkillPackager interface.
type MockSkillPackager struct {
	ctrl     *gomock.Controller
	recorder *MockSkillPackagerMockRecorder
	isgomock struct{}
}

// MockSkillPackagerMockRecorder is the mock recorder for MockSkillPackager.
type MockSkillPackagerMockRecorder struct {
	mock *MockSkillPackager
}

// NewMockSkillPackager creates a new mock instance.
func NewMockSkillPackager(ctrl *gomock.Controller) *MockSkillPackager {
	mock := &MockSkillPackager{ctrl: ctrl}
	mock.recorder = &MockSkillPackagerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSkillPackager) EXPECT() *MockSkillPackagerMockRecorder {
	return m.recorder
}

// Package mocks base method.
func (m *MockSkillPackager) Package(ctx context.Context, skillDir string, opts skills.PackageOptions) (*skills.PackageResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Package", ctx, skillDir, opts)
	ret0, _ := ret[0].(*skills.PackageResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Package indicates an expected call of Package.
func (mr *MockSkillPackagerMockRecorder) Package(ctx, skillDir, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Package", reflect.TypeOf((*MockSkillPackager)(nil).Package), ctx, skillDir, opts)
}
