# SPDX-FileCopyrightText: Copyright 2026 Stacklok, Inc.
# SPDX-License-Identifier: Apache-2.0

name: License Headers

on:
  workflow_call:

permissions:
  contents: read

jobs:
  check-license-headers:
    name: Check License Headers
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Set up Go
        uses: actions/setup-go@924ae3a1cded613372ab5595356fb5720e22ba16 # v6.5.0
        with:
          go-version: 'stable'
          cache: false

      - name: Install addlicense
        run: go install github.com/google/addlicense@latest

      - name: Check license headers
        run: |
          # Check all Go files for SPDX license headers
          addlicense -check \
            -f .github/license-header.txt \
            -ignore '**/mocks/**' \
            -ignore '**/testdata/**' \
            -ignore 'vendor/**' \
            -ignore '**/*.pb.go' \
            -ignore '**/zz_generated*.go' \
            $(find . -name '*.go' -type f)
